mail-sender:
  host: ${MAIL_SENDER_HOST}
  port: ${MAIL_SENDER_PORT:0}
  username: ${MAIL_SENDER_USERNAME}
  password: ${MAIL_SENDER_PASSWORD}
  protocol: ${MAIL_SENDER_PROTOCOL}
  auth: ${MAIL_SENDER_AUTH:true}
  starttls-enable: ${MAIL_SENDER_STARTTLS_ENABLE:true}
  debug: ${MAIL_SENDER_DEBUG:false}