mail-sender:
  host: localhost
  port: 1
  username: name
  password: pass
  protocol: ${MAIL_SENDER_PROTOCOL}
  auth: ${MAIL_SENDER_AUTH:true}
  starttls-enable: ${MAIL_SENDER_STARTTLS_ENABLE:true}
  debug: ${MAIL_SENDER_DEBUG:false}