# Generated by Django 3.2.9 on 2021-11-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_user',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
