# Generated by Django 3.2.9 on 2021-11-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0002_alter_register_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register_USER',
        ),
    ]
