# Generated by Django 3.2.9 on 2021-11-25 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0036_match_team_member_tourney_member'),
        ('app_profiles', '0003_alter_user_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='game',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sber_games.game'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teams',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sber_games.team'),
        ),
    ]
