# Generated by Django 3.2.9 on 2021-11-25 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0037_rename_user_team_member_users'),
        ('app_profiles', '0004_auto_20211125_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teams',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sber_games.team_member'),
        ),
    ]
