# Generated by Django 3.2.9 on 2021-11-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0004_register_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_user',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
