# Generated by Django 3.2.9 on 2021-11-14 09:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GAME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(default=None, upload_to='images/game/')),
            ],
            options={
                'db_table': 'GAMES',
            },
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(db_index=True, max_length=255)),
                ('fio', models.CharField(max_length=255)),
                ('tab_number', models.CharField(max_length=255)),
                ('game_account', models.CharField(max_length=255)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('game', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sber_games.game')),
            ],
            options={
                'db_table': 'USERS',
            },
        ),
        migrations.CreateModel(
            name='TOURNAMENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(default=None, upload_to='images/tournament/')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('start_date', models.DateTimeField()),
                ('members', models.CharField(default=None, max_length=2555)),
                ('prize', models.CharField(max_length=255)),
                ('chat_id', models.CharField(default=1, max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('game', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sber_games.game')),
            ],
            options={
                'db_table': 'TOURNAMENTS',
            },
        ),
        migrations.CreateModel(
            name='TEAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(default=None, upload_to='images/team/')),
                ('members', models.CharField(max_length=2555)),
                ('status', models.BooleanField(default=True)),
                ('game', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sber_games.game')),
            ],
            options={
                'db_table': 'TEAMS',
            },
        ),
    ]
