# Generated by Django 3.2.9 on 2021-11-14 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MEMBER_IN_TOURNAMENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournamt', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sber_games.tournament')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sber_games.user')),
            ],
            options={
                'db_table': 'MEMBER_IN_TOURNAMENT',
            },
        ),
    ]
