# Generated by Django 3.2.9 on 2021-11-14 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0002_member_in_tournament'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MEMBER_IN_TOURNAMENT',
            new_name='PARTICIPANTS_UTeam',
        ),
        migrations.AlterField(
            model_name='participants_uteam',
            name='tournamt',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sber_games.team'),
        ),
        migrations.AlterModelTable(
            name='participants_uteam',
            table='PARTICIPANTS_UTeam',
        ),
        migrations.CreateModel(
            name='PARTICIPANTS_UTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournamt', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sber_games.tournament')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sber_games.user')),
            ],
            options={
                'db_table': 'PARTICIPANTS_UTournament',
            },
        ),
    ]
