# Generated by Django 3.2.9 on 2021-11-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0003_auto_20211114_1049'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='participants_uteam',
            table='ParticipantsUserToTeam',
        ),
        migrations.AlterModelTable(
            name='participants_utournament',
            table='ParticipantsUserToTournament',
        ),
    ]
