# Generated by Django 3.2.9 on 2021-11-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0004_auto_20211114_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants_uteam',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='participants_utournament',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
