# Generated by Django 3.2.9 on 2021-11-11 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0004_auto_20211111_1940'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='games',
            table='GAMES',
        ),
        migrations.AlterModelTable(
            name='teams',
            table='TOURNAMENT',
        ),
        migrations.AlterModelTable(
            name='user',
            table='USERS',
        ),
    ]
