# Generated by Django 3.2.9 on 2021-11-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0005_auto_20211114_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fio',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='second_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.ImageField(default=None, upload_to='sber_games/images/game/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(default=None, upload_to='sber_games/images/team/'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(default=None, upload_to='sber_games/images/tournament/'),
        ),
    ]
