# Generated by Django 3.2.9 on 2021-11-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0005_auto_20211111_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOURNAMENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'TOURNAMENT',
            },
        ),
        migrations.AlterModelTable(
            name='teams',
            table='TEAMS',
        ),
    ]
