# Generated by Django 3.2.9 on 2021-11-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0010_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants_utournament',
            name='tournamt',
        ),
        migrations.RemoveField(
            model_name='participants_utournament',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='game',
        ),
        migrations.DeleteModel(
            name='PARTICIPANTS_UTeam',
        ),
        migrations.DeleteModel(
            name='PARTICIPANTS_UTournament',
        ),
        migrations.DeleteModel(
            name='USER',
        ),
    ]
