# Generated by Django 3.2.9 on 2021-11-14 14:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0011_auto_20211114_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.ImageField(default=None, upload_to='sber_games/images/game/', verbose_name=uuid.UUID('2a1c7f55-4235-44bd-8eab-659779ba5b11')),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(default=None, upload_to='sber_games/images/team/', verbose_name=uuid.UUID('d880c0a2-8cb5-42d4-8904-463a563664ed')),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(default=None, upload_to='sber_games/images/tournament/', verbose_name=uuid.UUID('dd138ed5-f836-4034-ba58-1d8ba7300f71')),
        ),
    ]
