# Generated by Django 3.2.9 on 2021-11-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0012_auto_20211114_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.ImageField(default=None, upload_to='sber_games/images/game/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(default=None, upload_to='sber_games/images/team/'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(default=None, upload_to='sber_games/images/tournament/'),
        ),
    ]
