# Generated by Django 3.2.9 on 2021-11-14 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0001_initial'),
        ('sber_games', '0013_auto_20211114_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='PARTICIPANTS_UTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('tournamt', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sber_games.tournament')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_profiles.user')),
            ],
            options={
                'db_table': 'ParticipantsUserToTournament',
            },
        ),
    ]
