# Generated by Django 3.2.9 on 2021-11-14 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0001_initial'),
        ('sber_games', '0014_participants_utournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='PARTICIPANTS_UTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournamt', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sber_games.team')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_profiles.user')),
            ],
            options={
                'db_table': 'ParticipantsUserToTeam',
            },
        ),
    ]
