# Generated by Django 3.2.9 on 2021-11-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0015_participants_uteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants_utournament',
            name='name',
        ),
    ]
