# Generated by Django 3.2.9 on 2021-11-14 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0016_remove_participants_utournament_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants_uteam',
            name='tournamt',
        ),
        migrations.RemoveField(
            model_name='participants_utournament',
            name='tournamt',
        ),
        migrations.AddField(
            model_name='participants_uteam',
            name='tournament',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sber_games.team'),
        ),
        migrations.AddField(
            model_name='participants_utournament',
            name='tournament',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sber_games.tournament'),
        ),
        migrations.AlterField(
            model_name='participants_uteam',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='participants_utournament',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
