# Generated by Django 3.2.9 on 2021-11-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0017_auto_20211114_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants_uteam',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='participants_utournament',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
