# Generated by Django 3.2.9 on 2021-11-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0018_auto_20211114_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants_uteam',
            name='tournament',
        ),
    ]
