# Generated by Django 3.2.9 on 2021-11-14 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0019_remove_participants_uteam_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants_uteam',
            name='tournament',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sber_games.tournament'),
        ),
    ]
