# Generated by Django 3.2.9 on 2021-11-18 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0001_initial'),
        ('sber_games', '0021_auto_20211114_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_profiles.user'),
        ),
    ]
