# Generated by Django 3.2.9 on 2021-11-18 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0022_alter_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='members',
        ),
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sber_games.team'),
        ),
    ]
