# Generated by Django 3.2.9 on 2021-11-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0032_alter_tournament_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(upload_to='sber_games/images/tournament/'),
        ),
    ]
