# Generated by Django 3.2.9 on 2021-11-23 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0033_alter_tournament_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants_utournament',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='participants_utournament',
            name='user',
        ),
        migrations.DeleteModel(
            name='PARTICIPANTS_UTeam',
        ),
        migrations.DeleteModel(
            name='PARTICIPANTS_UTournament',
        ),
    ]
