# Generated by Django 3.2.9 on 2021-11-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0034_auto_20211123_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='capitan',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
