# Generated by Django 3.2.9 on 2021-11-25 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0003_alter_user_game'),
        ('sber_games', '0035_team_capitan'),
    ]

    operations = [
        migrations.CreateModel(
            name='MATCH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_name', models.CharField(max_length=255)),
                ('team1_logo', models.CharField(max_length=255)),
                ('team2_name', models.CharField(max_length=255)),
                ('team2_logo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'MATCH',
            },
        ),
        migrations.CreateModel(
            name='TOURNEY_MEMBER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sber_games.team')),
                ('tournament', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sber_games.tournament')),
            ],
            options={
                'db_table': 'TOURNEY_MEMBER',
            },
        ),
        migrations.CreateModel(
            name='TEAM_MEMBER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sber_games.team')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_profiles.user')),
            ],
            options={
                'db_table': 'TEAM_MEMBER',
            },
        ),
    ]
