# Generated by Django 3.2.9 on 2021-11-25 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0036_match_team_member_tourney_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team_member',
            old_name='user',
            new_name='users',
        ),
    ]
