# Generated by Django 3.2.9 on 2021-11-25 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0037_rename_user_team_member_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourney_member',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='tourney_member',
            name='tournament',
        ),
        migrations.DeleteModel(
            name='TEAM_MEMBER',
        ),
        migrations.DeleteModel(
            name='TOURNEY_MEMBER',
        ),
    ]
