# Generated by Django 3.2.9 on 2021-11-25 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0039_tournament_users_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='users_members',
        ),
        migrations.AddField(
            model_name='tournament',
            name='members',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sber_games.team'),
        ),
    ]
