# Generated by Django 3.2.9 on 2021-11-25 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0040_auto_20211125_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tournamentdddd',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sber_games.tournament'),
        ),
    ]
