# Generated by Django 3.2.9 on 2021-11-25 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0041_team_tournamentdddd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='tournamentdddd',
        ),
        migrations.AddField(
            model_name='team',
            name='tournaments',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sber_games.tournament'),
        ),
    ]
