# Generated by Django 3.2.9 on 2021-11-25 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0006_alter_user_teams'),
        ('sber_games', '0042_auto_20211125_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='members',
            new_name='team_member',
        ),
        migrations.AddField(
            model_name='tournament',
            name='user_member',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_profiles.user'),
        ),
    ]
