# Generated by Django 3.2.9 on 2021-11-25 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0006_alter_user_teams'),
        ('sber_games', '0044_alter_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='team_member',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sber_games.team'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='user_member',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_profiles.user'),
        ),
    ]
