# Generated by Django 3.2.9 on 2021-11-25 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0045_auto_20211125_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team1_logo',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team1_name',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2_logo',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2_name',
        ),
        migrations.AddField(
            model_name='match',
            name='team_member',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sber_games.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournaments',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sber_games.tournament'),
        ),
    ]
