# Generated by Django 3.2.9 on 2021-11-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sber_games', '0047_remove_match_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
